### PR TITLE
Fix publish to PyPI

### PR DESCRIPTION
**Pull request by mjwen**
To install kimpy, kim-api should already be installed. This PR adds kim-api installing script to the GH publish action.

### CODE REVIEW

**Comment by mjwen** [comment]
This is still failing due to `Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.` https://github.com/openkim/kimpy/runs/1484043074?check_suite_focus=true

@ellio167 you have the PyPI credentials added, right? 

Also, we are only building and uploading Linux Py3.9 wheel, not for other systems. Should be OK for now; we can add more later.

**Comment by yafshar** [comment]
@ellio167 please change my secrets to yours or to openkim at [pythonpublish](https://github.com/openkim/kimpy/blob/5b80e0dea5b9e93392bd70edc5f6f02f4d531fee/.github/workflows/pythonpublish.yml)       
```py
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME_Y }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD_Y }}
```

**Comment by yafshar** [comment]
@ellio167 @mjwen I corrected the names to the openkim secrets. If the credentials have already been added it should work correctly.

**Comment by ellio167** [comment]
done!

**Pull request merged**
